    # ── NEW BATCH: Employment-specific risks ──────────────────────────────────

    {
        "id": "excessive_notice_period_employee",
        "pattern": r"(employee|you).{0,60}(notice\s+period|resign).{0,60}(9[0-9]|1[0-9]{2})\s*days?",
        "level": "medium",
        "reason": "Your required resignation notice period is unusually long, which can trap you in a job you want to leave.",
        "tip": "60 days is standard for most Indian roles. Negotiate this down or ask for a buyout option.",
        "confidence": 78,
        "requires_not": [],
    },
    {
        "id": "non_compete_broad",
        "pattern": r"(shall\s+not|not\s+permitted|prohibited\s+from).{0,80}(work|employ|engage).{0,80}(competitor|similar\s+business|same\s+industry).{0,80}(any\s+(location|country|state)|worldwide|globally|india)",
        "level": "high",
        "reason": "This non-compete clause is broad enough to potentially block you from your entire industry after leaving.",
        "tip": "Indian courts generally do not enforce broad post-employment non-competes. Consult a lawyer if this is used against you.",
        "confidence": 85,
        "requires_not": [],
    },
    {
        "id": "salary_withholding_full_notice",
        "pattern": r"(salary|wages|dues|full\s+and\s+final).{0,80}(withheld|not\s+(be\s+)?released|forfeited).{0,80}(notice\s+period|resignation|clearance)",
        "level": "high",
        "reason": "Your salary can be withheld entirely if you don't serve the full notice period, even for dues you've already earned.",
        "tip": "Earned wages generally cannot be withheld under the Payment of Wages Act. Ask for partial release of dues.",
        "confidence": 87,
        "requires_not": [],
    },
    {
        "id": "forced_resignation_clause",
        "pattern": r"(deemed\s+to\s+have\s+resigned|deemed\s+resignation|automatic\s+resignation).{0,80}(absence|non[-\s]?compliance|failure\s+to)",
        "level": "high",
        "reason": "You could be treated as having resigned automatically, without any formal process or chance to explain.",
        "tip": "This bypasses your right to due process before termination. Ask for a formal show-cause step to be added.",
        "confidence": 89,
        "requires_not": [],
    },
    {
        "id": "unpaid_overtime_mandatory",
        "pattern": r"(overtime|extra\s+hours|additional\s+hours).{0,80}(no\s+(additional|extra)\s+(pay|compensation)|without\s+(additional\s+)?compensation|unpaid)",
        "level": "medium",
        "reason": "You may be required to work extra hours without additional pay.",
        "tip": "Under most state Shops and Establishments Acts, overtime must be compensated at 1.5x-2x the normal rate.",
        "confidence": 76,
        "requires_not": [],
    },
    {
        "id": "bond_penalty_resignation",
        "pattern": r"(bond|training\s+cost|penalty).{0,80}(resign|leave|quit).{0,80}(rs\.?\s*[\d,]+|lakh|lakhs)",
        "level": "high",
        "reason": "You may owe a large financial penalty if you resign before a set period, tied to training or bond costs.",
        "tip": "Employment bonds are enforceable only if the amount reflects genuine costs incurred. Ask for an itemized breakdown.",
        "confidence": 83,
        "requires_not": [],
    },
    {
        "id": "confidentiality_overreach",
        "pattern": r"confidential(ity)?.{0,100}(perpetuity|indefinitely|forever|no\s+time\s+limit)",
        "level": "medium",
        "reason": "Your confidentiality obligation has no time limit, extending indefinitely beyond your employment.",
        "tip": "Ask for a reasonable time limit (e.g. 2-5 years post-employment) on confidentiality obligations.",
        "confidence": 74,
        "requires_not": [],
    },

    # ── NEW BATCH: Rental-specific gaps ────────────────────────────────────────

    {
        "id": "key_money_non_refundable",
        "pattern": r"(key\s+money|goodwill\s+(amount|payment)|advance\s+(amount|payment)).{0,80}(non[-\s]?refundable|not\s+refundable)",
        "level": "high",
        "reason": "A one-time 'key money' or goodwill payment is being taken with no refund, separate from your security deposit.",
        "tip": "This practice is often not legally protected. Get a receipt and clarify in writing whether any part is refundable.",
        "confidence": 80,
        "requires_not": [],
    },
    {
        "id": "no_rent_receipt",
        "pattern": r"(landlord|owner).{0,60}(not\s+obligated|no\s+obligation|not\s+required).{0,60}(issue|provide|give).{0,30}receipt",
        "level": "medium",
        "reason": "The landlord isn't required to give you rent receipts, which could hurt you if you ever need proof of tenancy or for tax purposes.",
        "tip": "Ask for monthly rent receipts to be made mandatory in the agreement.",
        "confidence": 72,
        "requires_not": [],
    },
    {
        "id": "utility_disconnection_threat",
        "pattern": r"(landlord|owner).{0,60}(disconnect|cut\s+off|stop).{0,60}(electricity|water|utilit)",
        "level": "high",
        "reason": "The landlord may be permitted to cut off your electricity or water supply as a way to force compliance.",
        "tip": "Disconnecting essential utilities to force a tenant out is illegal in most Indian states, regardless of what the agreement says.",
        "confidence": 90,
        "requires_not": [],
    },
    {
        "id": "unregistered_lockin_risk",
        "pattern": r"(agreement|lease).{0,60}(not\s+(be\s+)?registered|unregistered).{0,80}(1[2-9]|2\d|3\d)\s*(month|months|year|years)",
        "level": "medium",
        "reason": "This agreement runs longer than 11 months but states it won't be registered, which can weaken your legal standing in a dispute.",
        "tip": "Agreements over 11 months should legally be registered at the Sub-Registrar's office to be fully enforceable.",
        "confidence": 79,
        "requires_not": [],
    },
    {
        "id": "broker_fee_tenant_full",
        "pattern": r"(brokerage|broker\s+fee|agent\s+fee).{0,60}(entirely|fully|100\s*%|solely).{0,40}(tenant|lessee)",
        "level": "low",
        "reason": "You are bearing the full brokerage fee, which in some markets is customarily split with the landlord.",
        "tip": "Brokerage split norms vary by city — check local convention before accepting full liability.",
        "confidence": 60,
        "requires_not": [],
    },
    {
        "id": "painting_charges_deduction",
        "pattern": r"(painting|whitewash).{0,60}(charges?|cost).{0,60}(deduct|adjust).{0,40}(deposit|advance)",
        "level": "low",
        "reason": "Painting or whitewash charges will be deducted from your deposit regardless of the property's actual condition.",
        "tip": "Ask for deductions to be based on actual documented damage, not a flat mandatory charge.",
        "confidence": 65,
        "requires_not": [],
    },
    {
        "id": "pg_no_refund_partial_month",
        "pattern": r"(paying\s+guest|pg|hostel).{0,80}(no\s+refund|non[-\s]?refundable).{0,60}(partial|part\s+of\s+the\s+month|days\s+remaining)",
        "level": "medium",
        "reason": "You won't get any refund for unused days if you leave partway through a month.",
        "tip": "Ask for pro-rated refunds for the unused portion of any paid period.",
        "confidence": 70,
        "requires_not": [],
    },

    # ── NEW BATCH: Court notice / general legal risks ──────────────────────────

    {
        "id": "admission_of_liability",
        "pattern": r"(admit|acknowledge|accept).{0,60}(liability|guilt|fault|responsibility).{0,60}(without\s+prejudice)?",
        "level": "high",
        "reason": "This document may contain language where you admit liability or fault — this can be used against you later.",
        "tip": "Do not sign any document admitting fault or liability without a lawyer reviewing it first.",
        "confidence": 82,
        "requires_not": [r"deny|dispute|without\s+admitting"],
    },
    {
        "id": "ex_parte_risk",
        "pattern": r"ex[-\s]?parte.{0,80}(order|proceed|decree)",
        "level": "high",
        "reason": "This notice mentions an ex-parte order — a ruling that can be made against you if you don't respond in time.",
        "tip": "Respond within the stated deadline. Missing it may result in a decision being made without your side being heard.",
        "confidence": 88,
        "requires_not": [],
    },
    {
        "id": "limitation_period_warning",
        "pattern": r"(limitation\s+period|within\s+(30|thirty|15|fifteen|60|sixty)\s+days\s+of\s+(receipt|service)).{0,80}(respond|reply|file|appear)",
        "level": "high",
        "reason": "There's a strict legal deadline to respond to this notice — missing it can seriously harm your case.",
        "tip": "Note the exact deadline and consult a lawyer well before it expires.",
        "confidence": 85,
        "requires_not": [],
    },
